# -*- coding: utf-8 -*-
"""Titanic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sdpde-Pqml3G8np94fMkhpiF2NHKwV-t
"""

import pandas as pd

df = pd.read_csv("train.csv")

df.head()

df.info()

print(df.isnull().sum())

df.drop(columns=['Cabin'], inplace=True)

df['Age'] = df['Age'].fillna(
    df['Age'].median()
)

df['Embarked'] = df['Embarked'].fillna(
    df['Embarked'].mode()[0]
)

print(df.isnull().sum())

features = ['Pclass', 'Sex', 'Age', 'Fare', 'SibSp', 'Parch', 'Embarked']

X = df[features].copy()
y = df['Survived']

X['Embarked'] = X['Embarked'].map({'S': 0, 'C': 1, 'Q': 2})

print(X.isnull().sum())
print(X.head())

print(X['Sex'].unique())

print(X.head())

X['Sex'] = (
    X['Sex']
    .astype(str)
    .str.strip()
    .str.lower()
)
print(X['Sex'].unique())

print(X['Sex'].unique())

X['Sex'] = X['Sex'].replace({
    'male': 0,
    'female': 1
})
print(X.head())

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

from sklearn.linear_model import LogisticRegression

from sklearn.model_selection import cross_val_score

model = LogisticRegression()

scores = cross_val_score(
    model,
    X_train,
    y_train,
    cv=5
)

print("Fold Scores:")

print(scores)

print()

print("Average Accuracy:")

print(scores.mean())

model.fit(X_train, y_train)

print("Model Training Complete")

from sklearn.metrics import accuracy_score

y_pred = model.predict(X_test)

accuracy = accuracy_score(
    y_test,
    y_pred
)

print("Accuracy:", accuracy)

import pickle
from google.colab import files


# SAVE MODEL
with open("titanic_model.pkl", "wb") as f:
    pickle.dump(model, f)


# SAVE SCALER
with open("scaler.pkl", "wb") as f:
    pickle.dump(scaler, f)


print("Files Saved Successfully")


# DOWNLOAD FILES
files.download("titanic_model.pkl")
files.download("scaler.pkl")